### ISSUE TITLE
i3lock loses input focus in GNOME

### ISSUE THREAD

**Issue by soamaven** [i3/i3lock#113]
I used GNOME tweak tool to activate Windows>Automatically Raise Windows. If I have other applications open when I activate i3lock, the input focus is never on i3lock, and thus cannot enter my password to unlock. I can disable this setting, but I'd rather find a way not to, as I really love its impact on my workflow.

**Comment by Airblader** [comment]
Can you run i3lock under xtrace (sometimes called x11trace) and post the output of that here? I assume that i3lock and Gnome are fighting against here, because i3lock tries to raise its window anytime it is being obscured. This Gnome setting probably does the same.

If this is the case then there's nothing we can do without fully relying on compositing and using the compositing PR – but that's not something we want to do.

**Comment by soamaven** [comment]
I should maybe mention that I am using Wayland on Fedora 25. I have a feeling there are no guarantees about i3lock and Wayland?

**Comment by Airblader** [comment]
No. i3lock is written for X11. I don't know how it'll behave under Xwayland and we don't intend to support that.

**Comment by Airblader** [comment]
I think the sway project has a replacement for i3lock as well (swaylock), so you might want to give that a shot. It's written for Wayland.

**Comment by soamaven** [comment]
Thank you! I will try them out. Not unlikely these troubles are originating from Wayland.
