### ISSUE TITLE
Add an option to not blank/block/color the screen when locking (like xtrlock does)

### ISSUE THREAD

**Issue by Stefan24842** [i3/i3lock#211]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When you use i3lock, it replaced the currently visible windows with a color or an image.
## Expected Behavior

It would be nice if there was an option to lock the screen but not change it, i.e. let people see the screen content while the device is locked. (Basically what xtrlock does but with the nice i3lock features like the password indicator.)
It would be useful e.g. if you (or others) want to check the progress of some slow process on your device without having to unlock it.

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: `i3lock: version 2.11.1 © 2010 Michael Stapelberg`
</pre>

**Comment by eplanet** [comment]
I'm pretty sure that feature won't be added to `i3lock` itself. But you can achieve that very easily by wrapping the following into a script:
- take a screenshot using `scrot`
- display it as a background for `i3lock`
- delete the image after unlock

Example, save the following into `i3lock_screen.sh` and call it instead of `i3lock`:

```bash
#!/bin/bash

IMAGE=/tmp/i3lock.png
scrot $IMAGE
i3lock -i $IMAGE
rm $IMAGE
```

Some people are even [blurring the screen](https://gist.github.com/csivanich/10914698) so that sensitive informations are hidden.

**Comment by Airblader** [comment]
The method suggested by @eplanet of course won't help tracking an on-going process, but he is correct in that I don't think we want to add this to i3lock – it's a footgun, as you still leak information. I don't think the philosophy in i3lock fits that well, so I would suggest just using xtrlock in this case. Thanks for understanding!
