### ISSUE TITLE
Display the keyboard layout on the lock screen.

### ISSUE THREAD

**Issue by Liorst4** [i3/i3lock#287]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
The input language is not displayed on the screen. If you don't remember what was the input language when you locked the machine, you need to switch the language and try until it works.

## Expected Behavior
The input language should be displayed on the screen.

## Reproduction Instructions

```
setxkbmap -option grp:alt_shift_toggle us,es
# Press alt+shift a random amount of times
i3lock
# You have only 50% chance of unlocking the computer if you enter the right password.
```

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: 2.12
</pre>

**Comment by stapelberg** [comment]
We display when you press caps lock, so the keyboard layout falls into the same category.

Unfortunately, things aren’t so easy with keyboard layouts: desktop environments may have the concept of a configured/enabled keyboard layout, but i3 (or other window managers used without desktop environments) don’t have that.

Without such a list, the only thing we could do is display the current keyboard layout *all the time*, which seems excessive to me. Most users only use one keyboard layout, so why would we annoy them with an unhelpful bit of information in a prominent place?

That said, if seeing the keyboard layout at the time of the screen lock on your lock screen, one option you have is to overlay this information on an image yourself in a wrapper script that starts i3lock.

**Comment by stapelberg** [comment]
I’ll tentatively close this as I don’t see a good way of making it happen.

**Comment by orestisfl** [comment]
@Liorst4 you can run `[xkb-switch](https://github.com/grwlf/xkb-switch) -s us` prior to locking to make sure that the correct layout is enabled.

@stapelberg Aren't layouts part of XKB? What do DEs have to do with it?

**Comment by stapelberg** [comment]
> @stapelberg Aren't layouts part of XKB? What do DEs have to do with them?

Layouts are defined via XKB indeed.

What DEs can add is a dialog in which you select which keyboard layouts you actually want to use out of the ≈hundred that are available. This allows for chosing between, say, English and Russian (just 2 entries instead of 100s) in a drop-down (e.g. tray icon).

See the screenshots at http://linuxblog.darkduck.com/2013/10/how-to-configure-keyboard-layouts-in-unity-gnome3-kde.html if you’re unfamiliar.

**Comment by Liorst4** [comment]
```
$ setxkbmap -query
...
layout:     us,es
options:    grp:alt_shift_toggle
```
`setxkbmap` can tell when there is more than one layout, can't `i3lock` do the same thing?

**Comment by stapelberg** [comment]
This only queries which layout you have selected when you configure 2 layouts at the same time on the XKB level.

This is not a common config—instead of configuring 2 layouts at the same time, many just switch between layouts altogether. Switching altogether becomes necessary when you use layouts that make use of all XKB layers, e.g. https://neo-layout.org/

**Comment by rddunphy** [comment]
Could this be added as a command line option? Something like `i3lock --show-kbd-layout` to show the layout alongside the CapsLock indicator, for example. This way the feature is available to those of us who toggle between keyboard layouts a lot, without affecting the UX of other users.
