### ISSUE TITLE
Mod-key reset after screen lock.

### ISSUE THREAD

**Issue by rjeffman** [i3/i3lock#336]
## I'm submitting a…
<pre>
[X] Bug
[ ] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

I have swapped  L_ALT and WIN keys so that I can use "L_ALT+key" to execute window manager commands rather than "WIN+key" (e.g. "L_ALT + r" to resize). To swap the keys I have no my `.config/i3/config` file:
```
exec --no-startup-id setxkbmap -option altwin:swap_lalt_lwin
```

This works well until the screen is locked. Once I unlock by typing the password, the behavior of the keys is reverted until I run `setxkbmap` again.

## Expected Behavior

Keyboard settings are kept the same after unlocking screen.

## Reproduction Instructions

1. Run `exec --no-startup-id setxkbmap -option altwin:swap_lalt_lwin`
2. Lock screen
3. Unlock screen with pasword
4. Try `L_ALT + r`, resize mode should be enabled, but it isn't
 
## Environment
Output of `i3lock --version`:
<pre>
i3lock version: version 2.14.1 © 2010 Michael Stapelberg
</pre>

**Comment by stapelberg** [comment]
Can you describe what computer, monitor and keyboard you’re using when you run into this problem?

I’m asking because a common issue is that people connect their keyboard to their monitor’s USB hub, which is then turned off after people lock their screen. After logging in, the keyboard is enumerated again as a new USB device, but with default settings.

A variant of this problem is if you suspend your machine to RAM and the keyboard is re-enumerated on wakeup.

Either way, the fix is to make your configuration persistent: instead of running setxkbmap when i3 starts, change your /etc/X11/xorg.conf.d. For example, I use:

```
% cat /etc/X11/xorg.conf.d/00-keyboard.conf 
# Written by systemd-localed(8), read by systemd-localed and Xorg. It's
# probably wise not to edit this file manually. Use localectl(1) to
# instruct systemd-localed to update it.
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "de"
        Option "XkbVariant" "neo"
EndSection
```

**Comment by rjeffman** [comment]
Computer is a Lenovo ThinkPad T14s, keyboard is a Keychron K3 bluetooth keyboard. Monitor is irrelevant. I use 3 (notebook + 2), which are of different models and keyboard is not connected to any of them.

The cause might be the keyboard being enumerated again. `dmesg` has these entries related to the keyboard:
```
(...)
(...)0005:05AC:024F.0013/input/input50
(...)
(...)0005:05AC:024F.0014/input/input51
```

The problem is that I'm not setting the keyboard layout, only changing the behavior of two keys, and I don't want to do it system wide. I have not found a way to persist the change on a per user basis.

**Comment by stapelberg** [comment]
If you don’t want to do it system-wide, wrap i3lock in a script which calls the commands you need once the i3lock command returns. You can find an example wrapper in https://manpages.debian.org/i3lock.1, in the DPMS section.

**Comment by rjeffman** [comment]
Thank you. It worked well.
