### ISSUE TITLE
Pressing the power button exposes the contents of the screen for a short time.

### ISSUE THREAD

**Issue by c137v8** [i3/i3lock#366]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Pressing the hardware button on my laptop shows what was open before locking the screen just before the system shuts down

## Expected Behavior

The contents of the screen should not be shown as the hardware powerbutton is pressed
## Environment
Output of `i3lock --version`:
i3lock: version 2.14.1 © 2010 Michael Stapelberg

<pre>
i3lock version: 2.14.1 

</pre>

**Comment by stapelberg** [comment]
> Pressing the hardware [power] button on my laptop shows what was open before locking the screen just before the system shuts down

Shutting down your machine kills all running programs, including i3lock, which is why the screen lock disappears.

I don’t know how this could possibly be changed.

You could look into systemd’s inhibitor mechanism to see if you can prevent logind from powering off the system while your screen is locked. (I’m not sure if using xss-lock as the i3lock man page recommends is sufficient.) Alternatively, you can configure logind to not power off your system when the hardware button is pressed.
