### ISSUE TITLE
Feature request: Pass XF86Audio*-Keys to i3

### ISSUE THREAD

**Issue by bebehei** [i3/i3lock#52]
While the password is locked, pass the special keys to play/pause/mute/... the music to i3.
You don't have to type the password anymore to access the mediaplayer.

**Comment by Airblader** [comment]
This assumes that those keys are bound to those functions, which they might not be. Hence this introduces a security risk. Ill close for that reason.

**Comment by bebehei** [comment]
That's correct. Adding this without any configuration options will imply a security risk.

It would be great if you could give i3lock via options or configuration file some keystrokes, which are ok to pass to the wm while locked.

**Comment by Airblader** [comment]
I don't think we want this kind of configurability in i3lock which we generally keep to be simple and safe. @stapelberg Agreed?

**Comment by stapelberg** [comment]
Agreed.

@bebehei If you want features like this, a more full featured desktop environment/screen locker might provide them.

**Comment by avindra** [comment]
Has anyone found a workaround for this? Or can suggest an alternative locker?

**Comment by alecdwm** [comment]
FYI: this issue appears to have been fixed in [i3lock-color](https://github.com/chrjguill/i3lock-color)

**Comment by bebehei** [comment]
@alecdwm No, this seems not to be fixed. But while viewing the changes, I got enough knowledge about `i3lock.c` to know where to patch it in a hardcoded manner.

At least it "works for me". See e4f21193f5204dccad71715b1d69dd3f25f1e48c

Thank you for your notification. I now had been able to fix it. I'm so happy.

**Comment by tsuflux** [comment]
If anyone is interested in a less hardcoded version than @bebehei's, have a look at da6bc935027128ffac429e49b11a3b2ad9a0afbf. I have added an option to pass some XF86Audio* keys through to the root window by using `xcb_send_event`.

**Comment by bebehei** [comment]
@tsuflux Well, have you opened a pull request?

**Comment by luislobo** [comment]
@stapelberg well, I partially agree, but:
- i3 is not run by normal regular users, normally people that know what they are doing
- the change in the commit needs a particular specific parameter to be set so that i3lock passes through those keys, it's not the "standard" mode.
- If an i3 kind of user doesn't know what their multimedia keys are doing (specially since you have to specifically configure the multimedia keys in i3 for them to work)... well, you are already in trouble.

**Comment by kpcyrd** [comment]
I think the original concern by @Airblader was about passing those keys by default. Since 4d85b886fc16376c85c9ea444ca6b9c0a65cccc5 is opt-in, the only risk is somebody explicitly enabling this feature without testing what those keys do on their setup. I think being able to quickly mute audio is a very reasonable request.

**Comment by stapelberg** [comment]
We’d like to keep the option surface as small as possible, and i3lock as secure as possible.

Any feature (such as this one) which allows you to intentionally or accidentally weaken your computer’s security has to be carefully considered, and this one just doesn’t tip the scales favorably enough for adding it, sorry.

**Comment by luislobo** [comment]
That's fine. I'll just fork it.

**Comment by aiguofer** [comment]
Encountered this same issue. Found that the proposed commit presented here has been merged into https://github.com/PandorasFox/i3lock-color so you can just pass the `--pass-media-keys` option.

Hooray for forks and open source :) thanks everyone!

**Comment by eduncan911** [comment]
Just to kindle a flame...  I agree 100% with the reasons to keep it out, for security (and speed).  

What the community does not agree with is the unilateral "nope, never" from the maintainers. This isn't healthy for any OSS project - rejecting what the community has obviously had issues with for 10+ years and proposed multiple fixes (this issue is 9 years old, and I've had these issues with i3 since then).

We, the community, humbly request a change in this project's security posture to that of QubesOS - which we all would agree is pretty much the most secure thing out there.  There approach?

* Give nothing, lock it all down.
* You want a keyboard?  You enable your SPI keyboard.
* You want a usb hub enabled on the motherboard?  You enable that usb hub ID on the motherboard.
* You want a usb mouse?  Well, first enable that usb hub ID before, and pick your mouse ID here to lock it down.
* You want Anti-Evil Maid?  Ok, do you want a USB keyboard?  Yes?  Then, no.  ROFL.

...etc.

The point is to keep an absolute secure posture: not even sane defaults, INSANE defaults for a lockscreen!  

...however, the package maintainers should adopt a more healthy stance to OSS and security, and allow users to configure overrides.

It will not be any more "accidentally insecure" any more then [adding your USB keyboard to an anti-evil maid attempt (a misnomer)](https://www.qubes-os.org/doc/anti-evil-maid/).

**Comment by stapelberg** [comment]
I can understand your frustration. It’s always annoying when software doesn’t match what you want it to do.

However, I want to push back on your “nope, never” characterization. Quoting from the previous messages that rejected the feature:

> Feel free to use a fork with this feature, but **for now**, I don’t think we want this in i3lock.

> this one just **doesn’t tip the scales favorably enough** for adding it, sorry.

I think these are sufficiently nuanced replies.

FWIW, we have reversed decisions in i3 when enough community interest was obvious, see e.g. window icons in titlebars or the merge of i3-gaps into i3.

But ultimately, it’s up to us where to draw the line. We’re not owing anyone anything. In particular, we’re not owing our free labor to maintain features that we don’t think fit the philosophy of our project.

If you want a pragmatic solution, use i3lock-color.

Thanks for your understanding.
