### ISSUE TITLE
Multihead display, stuck on verifying

### ISSUE THREAD

**Issue by moore3071** [i3/i3lock#70]
## Description

Given a dual-monitor system with i3lock active, when unlocking the screen my main monitor continued to display the 'verifying' circle and was unusable. My second monitor was still accessible (although I restarted the system instead of seeing if killing i3lock worked). 
## Behaviour
- main monitor displays verifying
- main monitor displays the i3bar
- main monitor is inaccessible
- second monitor is unlocked and usable
- keyboard shortcuts don't work when main monitor is in focus
## Expected behaviour
- i3lock exits and releases all control
## Reproducing

This error occurred randomly after using i3lock hundreds of time before. Unfortunately I have no steps to help reproduce the error as this has only happenned to me once

**Comment by stapelberg** [comment]
I’m not yet convinced this is an i3lock problem. Killing i3lock to see whether the problem disappeared would’ve been a really valuable test.

Issues with your graphics driver and/or x server could also manifest themselves like what you’re describing.

For completeness, which i3lock version are you using?

**Comment by moore3071** [comment]
i3lock version: 2.7

**Comment by MasterSergius** [comment]
Very similar problem - occurs only on two monitors. If I lock system with i3lock, I still can switch to another tty (one of 1-6) and it is unlocked! Just console, where I logged in, so anyone can access my computer in such way.

**Comment by Airblader** [comment]
@MasterSergius Of course you can always switch to another TTY. But other TTYs are unusable unless you logged in to them. And if you did that, you should lock them.

There's nothing i3lock can do here as this keybinding isn't under its control. That keybinding comes straight from the kernel.

**Comment by viking** [comment]
I had this same problem. I changed to another TTY and killed i3lock, but when I switched back, the verifying screen was still there. I couldn't do anything except kill i3wm to end the session and re-login.

**Comment by viking** [comment]
I am using i3lock version 2.6.

**Comment by bblough** [comment]
Another data point - two monitors and i3lock 2.8-1 (from Debian testing), and I was not unable to unlock my system today.  However, after switching to another tty and killing i3lock, I was still stuck at the lock screen.  Based on @stapelberg 's earlier comment, I believe this indicates that it's not an i3lock problem, at least, not in my case. (I obviously can't speak for anyone else).

**Comment by moore3071** [comment]
It's been a while, but it's the first time I've been able to replicate the issue. Indeed after I killed i3lock and xautolock the verify screen persisted. Given that behaviour I'm inclined to believe this isn't an i3lock problem.

i3lock version: 'version  © 2010 Michael Stapelberg'
i3 version: i3 version 4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors

I'll close this issue now, although I'd love your input on what you think might be causing this, @stapelberg.

**Comment by seanparsons** [comment]
Interesting, I've just started experiencing this, oddly I _think_ my vconsole systemd service is failing.

**Comment by seharris** [comment]
I think I'm seeing the same problem on a system with only a single display.
Maybe once in every  few hundred unlocks the screen gets stuck at "verifying...", even after killing i3lock from the TTY.
I've had this happen a few times now, over the course of a few months.
Using i3-msg to send the "restart in place" command fixed my session the last time it happened.

i3lock: version 2.9.1 (2017-06-21) © 2010 Michael Stapelberg
i3 version 4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
(Arch Linux)

**Comment by primeos** [comment]
# Possible workaround for this bug

1) Switch to another VT and log in on the console.
3) Kill the `i3lock` process (and confirm it worked)
2) Find the location of the `i3` socket (on my system it was `/run/user/<uid>/i3/ipc-socket.<pid>`).
3) Start `i3lock` with the following command: `i3-msg -s <socket-path> exec i3lock`
4) Go back to your graphical VT where `i3` is running
5) Now you should be able to enter your password like normally and get back to your `i3` session.

### What I noticed (sadly not much...)

I just hit this bug as well. After entering the password (should've been the correct password) `i3lock` was stuck on "verifying...". I'm using two monitors: The primary monitor of my laptop (FullHD via eDP) and a secondary FullHD monitor that mirrors my primary monitor and is connected via an USB-C to HDMI adapter. I had some other X11 issues in the past but I could fix all of them by switching to another VT (required using the SysRq keys to exit the raw mode) and than back to the graphical VT where i3 is running. Since I couldn't find anything suspicious in the X11 log I'm not sure if it's really an X11 issue. But since killing `i3lock` doesn't fix the problem either it probably isn't related to `i3lock` as well. I then continued to issue some commands with `i3-msg` via another VT and everything worked fine (e.g. success after issuing reload).

Could it be possible that `i3lock` keeps a lock on the screen (and possibly the keyboard) that prevents the `i3` process from updating it or something like that?

**Comment by JonnyMako** [comment]
I can consistently reproduce this issue with a multi-monitor setup. If there is anything I can try to get some useful logs, please let me know. It will be nice to track this down to whatever program is causing this. Thanks.

**Comment by stapelberg** [comment]
@JonnyMako 
* Are you using i3lock 2.9.1?
* Is the issue reproducible under a new UNIX user account, i.e. without any of your dotfiles?
* Is the issue reproducible with the “vesa” driver (ruling out whichever Xorg driver you’re currently using as a culprit)?
* Is the issue reproducible with just one monitor?
* When i3lock hangs, can you attach gdb (using `gdb $(which i3lock) -p $(pidof i3lock)` and provide the result of `backtrace full` please? This requires the i3lock debugging symbols, which might be in a different package depending on your distro.

**Comment by jtlindsey** [comment]
> changed to another TTY and killed i3lock

How do you get to another terminal if i3lock won't unlock? Are you just sshing to the machine? I am using i3 on a dual monitor setup and sometimes it won't unlock with correct password

**Comment by Airblader** [comment]
Switching TTYs happens in the kernel, i3lock cannot prevent that from happening as the keys are intercepted by the kernel. You cam do that with Ctrl+Alt+F<n> to get to the n-th TTY. Where your current session is running depends a little bit on your setup.

**Comment by jtlindsey** [comment]
I think because i have i3 installed with xubuntu, i3lock is not allowing me to access terminal via Crtl+Alt+T or F key options. Ctrl+Alt+F1 works though.
