### ISSUE TITLE
Update background image on change

### ISSUE THREAD

**Issue by ChoiZ** [i3/i3lock#79]
Is it possible to update the background image on change when ilock already launch?

**Comment by Airblader** [comment]
What do you mean with "on change"? What changes?

**Comment by ChoiZ** [comment]
I listen RadioZone.fr webradios and I've made an imagemagick script to display current song / cover on air.
So my "background.png" is update on track change.

**Comment by Airblader** [comment]
I see. I don't quite understand why you need the current song displayed on the lock screen since the lock screen is typically activated when you *aren't* at your machine. But either way, this falls purely into an eye candy category. i3lock tries to stay away from such changes to keep the code as small as possible since it is a security-relevant application.

So the answer to the question whether this is possible is "No" and in terms of a feature request we don't want this for the above mentioned reasons. Therefore closing this issue.

**Comment by ChoiZ** [comment]
Ok I understand thanks for your answer ;-)
