### ISSUE TITLE
Unlock i3lock using a script

### ISSUE THREAD

**Issue by raphael** [i3/i3lock#87]
I would like to use i3lock with [blueproximity](http://www.webupd8.org/2011/05/blueproximity-use-bluetooth-device-to.html) and have my laptop unlock when my phone is within a certain distance.

I tried using the following script:
```bash
#!/bin/bash
LOCKFILE=/home/raphael/.i3lock
if [ -e $LOCKFILE ]; then
    kill `cat $LOCKFILE`
    rm -f $LOCKFILE
fi
```
where `/home/raphael/.i3lock` is created with:
```bash
#!/bin/bash
LOCKFILE=/home/raphael/.i3lock
i3lock --nofork --color=A0A0AA &
echo $!>$LOCKFILE
```
However the unlock script fails with:
```
unlock: line 6: kill: (8106) - No such process
```
I was hoping using the `--nofork` option would return the right pid but it doesn't seem like it.

How can I unlock the screen using scripts?

**Comment by stapelberg** [comment]
Run `killall i3lock`, which will kill all i3lock processes running as your user. Since you’ll always have at most 1 i3lock process, this should work.

**Comment by raphael** [comment]
duh - thanks!

**Comment by kmanwar89** [comment]
Hey raphael, can you help me get this set up?  This is really interesting and I was playing with blueproximity, got it locking my screen but I'm not sure how to pass my password to i3lock....currently using i3lock-fancy if that makes any difference.  Thanks!

**Comment by yakir12** [comment]
Sorry to open this again. I appreciate any help you might be able to provide, because this doesn't necessarily have to do with `i3lock` as much as `blueproximity` (so I'll understand if you just close this), but after setting
```
unlock_command = killall i3lock
```
in `~/.blueproximity/standard.conf` the screen never unlocks. In the terminal that spawned `blueproximity` I get 
```
i3lock: no process found
``` 
While in `blueproximity`'s log it doesn't complain:
```
Tue Sep 10 15:13:51 2019 blueproximity: screen is unlocked
```

which leads me to believe that maybe this has to do with who is trying to kill `i3lock`..?

Doing this, for instance, works as expected (lock, 1 second, unlock):
```
i3lock; sleep 1; killall i3lock
```

**Comment by yakir12** [comment]
Bump?
